import os
import csv

# Path to the additional training CSV
csv_path = r"d:\XuanDuc\TaiLieuKi8\CuoiKiHocSau\data\additional_train.csv"

# High-quality Vietnamese fake news and scam messages targeting authority impersonation and lucky draw scams
new_samples = [
    # 1. Impersonation of Government Authorities / Public Services
    ("CẢNH BÁO KHẨN CẤP TỪ BỘ CÔNG AN: Hiện tại cơ quan điều tra đang tiến hành rà soát toàn bộ các tài khoản ngân hàng có dấu hiệu nhận tiền bất chính từ nước ngoài. Số tài khoản của ông/bà đang nằm trong danh sách đen nghi vấn rửa tiền của vụ án lớn. Yêu cầu truy cập ngay cổng thông tin điện tử csgt-bo-cong-an-xacminh.com để cung cấp tên đăng nhập và mật khẩu ngân hàng trực tuyến nhằm phục vụ công tác đối soát khẩn cấp. Nếu trì hoãn hoặc bất hợp tác, tài khoản sẽ bị phong tỏa vĩnh viễn và bị khởi tố hình sự.", 1),
    ("Tòa án nhân dân tối cao gửi lệnh triệu tập khẩn cấp đối với công dân do có liên quan trực tiếp đến vụ án mua bán trái phép chất ma túy và rửa tiền của bị án Trịnh Văn Quyết. Yêu cầu liên hệ ngay với số điện thoại đường dây nóng của thanh tra tòa án để xác minh số dư tài khoản và chuyển tạm thời toàn bộ số tiền tiết kiệm sang tài khoản tạm giữ của cơ quan tư pháp để đối soát thanh tra.", 1),
    ("Bộ Y tế ra thông báo khẩn số 142/TB-BYT: Phát hiện ổ dịch virus corona biến thể mới cực kỳ nguy hiểm có khả năng kháng mọi loại vắc xin hiện tại, gây tử vong trong vòng 48 giờ. Đề nghị người dân hạn chế ra đường, khẩn trương đăng ký nhận kit test nhanh miễn phí và hỗ trợ y tế tại website của Bộ tại địa chỉ: boyte-dangky-kit.xyz.", 1),
    ("Tổng cục Thuế thông báo: Hộ kinh doanh của bạn nằm trong danh sách thanh tra thuế định kỳ năm nay vì nghi vấn kê khai gian lận hóa đơn điện tử. Yêu cầu tải app 'Thuế Điện Tử Việt Nam' tại đường link apk-gdt.cc để cập nhật thông tin quyết toán thuế trực tuyến, tránh bị xử phạt hành chính và đình chỉ hoạt động kinh doanh.", 1),
    ("Cục Cảnh sát giao thông thông báo phạt nguội: Phương tiện của bạn đã vi phạm luật giao thông đường bộ nghiêm trọng (vượt đèn đỏ tốc độ cao và va chạm gây tai nạn rồi bỏ chạy) vào lúc 14h30 ngày 25/05. Yêu cầu truy cập phatnguoi-csgt-xacminh.com để tra cứu biên bản phạt nguội và làm theo hướng dẫn thanh toán trực tuyến tiền phạt 15 triệu đồng trong 24 giờ, quá hạn sẽ bị khởi tố hình sự.", 1),
    ("Thông báo khẩn từ Bảo hiểm Xã hội Việt Nam: Cơ quan BHXH đang thực hiện chi trả trợ cấp thất nghiệp và hỗ trợ khó khăn quý II năm nay cho người lao động. Yêu cầu bạn nhấp vào liên kết bhxh-trocap-online.net để điền số Căn cước công dân và liên kết tài khoản ngân hàng nhận ngay số tiền hỗ trợ 3.500.000đ trước ngày 30/05.", 1),
    ("Công an thành phố Hà Nội phát đi lệnh triệu tập đặc biệt đối với công dân liên quan đến đường dây lừa đảo tài chính quy mô lớn. Yêu cầu công dân tải ứng dụng giám sát an ninh 'Bộ Công An' theo link m.bocongan-app.net để xác thực dấu vân tay và quét khuôn mặt online phục vụ công tác điều tra không công khai.", 1),
    ("Viện kiểm sát nhân dân tối cao ra quyết định tạm giam 3 tháng để phục vụ công tác điều tra đường dây rửa tiền quốc tế. Quyết định sẽ có hiệu lực thi hành sau 24h. Để chứng minh sự trong sạch và hoãn thi hành lệnh, yêu cầu chuyển toàn bộ tiền mặt hiện có sang tài khoản giám sát của Viện kiểm sát số 093848182 tại ngân hàng Agribank để thanh tra tài chính.", 1),
    ("Tổng công ty Điện lực miền Bắc (EVN NPC) thông báo khẩn: Hệ thống ghi nhận hộ gia đình của quý khách nợ tiền điện kỳ gần nhất là 2.450.000đ. Do quá hạn thanh toán nên chúng tôi sẽ tiến hành cắt điện sau 2 giờ nữa kể từ lúc nhận tin nhắn này. Đề nghị liên hệ ngay tổng đài chăm sóc khách hàng giả lập số 1900-xxxx hoặc chuyển tiền trực tiếp vào tài khoản cá nhân của thủ quỹ.", 1),
    ("Sở Giáo dục và Đào tạo thông báo khẩn cấp gửi các bậc phụ huynh học sinh: Đang xảy ra trường hợp nhiều học sinh bị tai nạn chấn thương sọ não cấp cứu tại bệnh viện Chợ Rẫy và cần tiền mổ gấp. Đề nghị các phụ huynh nhận được thông báo này khẩn trương chuyển khoản trước số tiền 50 triệu đồng vào tài khoản của bác sĩ điều trị số 102948281 để tiến hành phẫu thuật cứu mạng cháu.", 1),
    ("Bộ Thông tin và Truyền thông thông báo: Số điện thoại thuê bao của quý khách đang phát tán lượng lớn tin nhắn rác lừa đảo và tin tức chống phá Nhà nước. Thuê bao của quý khách sẽ bị khóa vĩnh viễn cả hai chiều sau 1 giờ nữa. Để được mở khóa và giải trình, yêu cầu liên hệ ngay tổng đài xử lý vi phạm viễn thông tại liên kết: tongdai-cuchuyenthot.info.", 1),
    ("Cục An ninh mạng và Phòng chống tội phạm công nghệ cao phát hiện tài khoản mạng xã hội của bạn chứa nội dung vi phạm luật an ninh mạng nghiêm trọng. Yêu cầu bạn tự giác khai báo thông tin cá nhân và mật khẩu Facebook, Zalo qua mẫu tờ khai trực tuyến tại link an-ninh-mang-viet-nam.com để tránh bị xử lý hình sự và phạt tiền từ 20 đến 30 triệu đồng.", 1),
    ("Tổng công ty Cấp nước Sài Gòn SAWACO thông báo: Hóa đơn tiền nước nhà bạn đã quá hạn thanh toán. Chúng tôi sẽ tạm ngừng cấp nước sinh hoạt vào sáng mai. Vui lòng thanh toán trực tiếp qua link thanh-toan-sawaco.online để cập nhật trạng thái đóng tiền nước ngay lập tức.", 1),
    ("Bộ Tài chính thông báo chương trình giảm thuế VAT và hoàn thuế thu nhập cá nhân tự động đối với người lao động có mức lương dưới 15 triệu đồng/tháng. Đề nghị bạn cung cấp thông tin tài khoản ngân hàng và mã OTP xác thực tại đường link hoanthuethunhap.xyz để hoàn tất thủ tục nhận tiền hoàn thuế.", 1),
    ("Cơ quan Cảnh sát điều tra Bộ Công an thông báo: Bạn đang có liên quan trực tiếp đến vụ án buôn lậu và trốn thuế của Tập đoàn Vạn Thịnh Phát. Yêu cầu hợp tác điều tra bằng cách tải phần mềm bảo mật thông tin có tên 'Cổng dịch vụ công Bộ Công An' tại csgt-gov.cc để tự động kiểm tra tính hợp pháp của dòng tiền trong tài khoản của bạn.", 1),

    # 2. Fake Giveaways, Promotions, and Lucky Draw Scams
    ("Vietnam Airlines chúc mừng sinh nhật lần thứ 30: Hãng hàng không quốc gia tặng 2 vé máy bay khứ hồi miễn phí cho tất cả khách hàng tham gia khảo sát nhanh tại liên kết: vietnamairlines-trian.com. Số lượng quà tặng có hạn, nhanh tay chia sẻ cho 3 người bạn và nhận mã vé điện tử miễn phí ngay hôm nay!", 1),
    ("Sự kiện tri ân Shopee 2026: Chúc mừng tài khoản của bạn đã được hệ thống lựa chọn ngẫu nhiên để nhận giải Đặc Biệt là 1 chiếc điện thoại iPhone 15 Pro Max trị giá 35 triệu đồng cùng voucher mua sắm 5 triệu đồng. Truy cập ngay shopee-awards2026.net để điền thông tin địa chỉ giao nhận quà miễn phí tại nhà.", 1),
    ("Thành viên may mắn nhận quà tặng Momo tri ân khách hàng: Nhận gói quà tặng thanh toán đa năng trị giá 2.000.000đ khi thực hiện liên kết tài khoản ngân hàng trực tuyến tại trang ưu đãi lớn: momo-trian-khachhang.com. Quà tặng áp dụng cho tất cả dịch vụ thanh toán hóa đơn điện nước, mua vé xem phim, ăn uống.", 1),
    ("Tập đoàn Vingroup tri ân khách hàng nhân kỷ niệm thành lập: Tặng ngay voucher mua xe máy điện VinFast Feliz S miễn phí trị giá 30 triệu đồng cho 100 khách hàng đầu tiên đăng ký tại trang sự kiện vinfast-feliz-trian.com và chia sẻ bài đăng này lên trang cá nhân ở chế độ công khai.", 1),
    ("Chúc mừng bạn đã trúng thưởng giải nhất trong chương trình quay số may mắn của Tổng công ty Viễn thông Viettel. Giải thưởng là 1 chiếc xe máy Honda SH 125i và phiếu mua hàng siêu thị trị giá 20 triệu đồng. Vui lòng truy cập trang chuongtrinhtrian-viettel.com để nộp lệ phí làm hồ sơ nhận giải là 1.000.000đ bằng thẻ cào điện thoại.", 1),
    ("Thế Giới Di Động tặng quà miễn phí: Tặng 200 chiếc đồng hồ thông minh Apple Watch SE cho những khách hàng may mắn tham gia trả lời câu hỏi khảo sát tại liên kết thegioididong-khuyenmai.net. Hãy nhanh tay bấm vào link, trả lời 3 câu hỏi đơn giản để nhận quà tận nơi.", 1),
    ("Thông báo khẩn cấp từ Facebook Việt Nam: Tài khoản cá nhân của bạn đã trúng giải Nhì chương trình tri ân cuối năm của Meta gồm 1 chiếc xe máy Honda Air Blade và 150 triệu đồng tiền mặt. Để làm thủ tục nhận giải và chuyển khoản tiền mặt, yêu cầu điền thông tin đầy đủ vào biểu mẫu tại trang web nhangiaifacebook2026.com.", 1),
    ("Ngân hàng Vietcombank gửi chương trình ưu đãi lớn: Nhận ngay 500.000đ tiền mặt cộng vào tài khoản thanh toán khi mở ứng dụng VCB Digibank qua liên kết giới thiệu: vcb-digibank-trian.net và thực hiện xác thực thông tin tài khoản eKYC trực tuyến bằng quét khuôn mặt và Căn cước công dân.", 1),
    ("Sự kiện tặng quà tri ân từ Samsung Việt Nam: Cơ hội sở hữu siêu phẩm Samsung Galaxy S24 Ultra hoàn toàn miễn phí. Chỉ cần truy cập samsung-trian-s24.com, chọn hộp quà may mắn và nhập thông tin địa chỉ nhà cùng số điện thoại liên hệ để nhân viên giao hàng chuyển phát nhanh đến tận nơi.", 1),
    ("Bia Heineken tri ân người tiêu dùng nhân dịp hè rực rỡ: Tặng 1000 thùng bia Heineken miễn phí và cơ hội trúng chuyến du lịch Châu Âu trị giá 100 triệu đồng. Hãy bấm vào link heineken-he-rucro.online để quay vòng quay may mắn nhận thưởng ngay lập tức.", 1),
    ("Coca-Cola Việt Nam mở thưởng tri ân khách hàng: Cơ hội trúng ngay xe máy Honda Vision và hàng ngàn thẻ cào điện thoại mệnh giá 500.000đ. Nhấp chuột vào link coca-cola-trian-2026.net để tham gia mở nắp chai ảo nhận giải ngay hôm nay!", 1),
    ("Hãng hàng không Vietjet Air kỷ niệm mở đường bay mới: Tặng 500 vé máy bay 0 đồng cho các chặng bay nội địa và quốc tế. Click vào link vietjetair-ve-0dong.com đăng ký thông tin cá nhân và nhận mã đặt chỗ miễn phí ngay bây giờ.", 1),
    ("Mạng di động Vinaphone tri ân thuê bao lâu năm: Tặng ngay gói data 4G tốc độ cao không giới hạn sử dụng trong 1 năm và 500.000đ tiền cước cuộc gọi. Đăng nhập tài khoản VinaPhone của bạn tại vinaphone-trian-goidata.com để nhận ưu đãi đặc biệt.", 1),
    ("Ngân hàng Techcombank thông báo: Quý khách đã nhận được quà tặng tri ân là 1 sổ tiết kiệm trị giá 10.000.000đ. Vui lòng đăng nhập tài khoản Mobile Banking của bạn tại techcombank-quatang.com để kích hoạt sổ tiết kiệm trực tuyến và rút tiền mặt.", 1),
    ("Ứng dụng gọi xe Grab tặng mã giảm giá khủng: Nhận ngay 10 mã giảm giá 100% (tối đa 50.000đ) cho các chuyến đi GrabCar hoặc GrabBike và 5 mã miễn phí giao đồ ăn GrabFood. Đăng ký thông tin tài khoản Grab tại grab-makhuyenmai-trian.net để nhận ưu đãi.", 1),
    ("Hệ thống siêu thị Coopmart tri ân khách hàng thân thiết: Tặng phiếu mua hàng trị giá 2.000.000đ áp dụng mua sắm trên toàn bộ hệ thống siêu thị Coopmart toàn quốc. Truy cập coopmart-trian-voucher.net để nhận mã phiếu mua hàng điện tử.", 1),
    ("Thương hiệu thời trang Adidas Việt Nam kỷ niệm ngày thành lập: Tặng 1000 đôi giày thể thao Adidas Ultraboost miễn phí cho người dùng chia sẻ tin nhắn này đến 10 bạn bè và nhấp vào liên kết adidas-giay-mienphi.com đăng ký size giày.", 1),
    ("Bưu điện Việt Nam VNPost thông báo: Bạn có một bưu phẩm chứa tiền mặt và giấy tờ quan trọng gửi từ nước ngoài chưa được nhận do sai thông tin địa chỉ. Vui lòng truy cập vnpost-buupham-xacminh.com đóng phí lưu kho và cập nhật địa chỉ giao hàng.", 1),
    ("Chúc mừng bạn đã trở thành người may mắn trúng giải nhất tuần từ chương trình Quay số trúng thưởng của ZaloPay. Giải thưởng trị giá 50 triệu đồng tiền mặt được chuyển trực tiếp vào tài khoản ngân hàng liên kết. Truy cập zalopay-nhangiai-2026.net để hoàn tất hồ sơ.", 1),
    ("Ngân hàng BIDV chúc mừng khách hàng nhận ưu đãi kỷ niệm thành lập: Tặng ngay 1 triệu đồng tiền mặt vào tài khoản cho khách hàng đăng nhập cổng trực tuyến bidv-trian-khuyenmai.com và xác thực OTP thành công. Chương trình chỉ diễn ra trong ngày hôm nay.", 1)
]

print(f"Opening {csv_path} to append {len(new_samples)} new scam and impersonation samples...")

# Open the file in append mode with correct encoding and newline handling
with open(csv_path, mode='a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    for sample, label in new_samples:
        writer.writerow([sample, label])

print("Data successfully appended!")
